language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g gulp
install:
  - "cd poller/; npm install; cd .."
  - "cd web/; npm install; cd .."
before_script:
  - "npm install -g gulp"
script: "gulp --gulpfile poller/gulpfile.js test"