---
- name: "Updating apt-get cache"
  apt: update_cache=yes cache_valid_time=3600

# Use force=yes to deal with unauthenticated packages on the raspberry
- name: "Installing MongoDB package"
  apt: name=mongodb state=present force=yes
  notify: restart mongodb

- name: "Configuring MongoDB to bind to external IP"
  lineinfile: dest={{mongo_db_conf}} regexp=^bind_ip line="bind_ip = {{mongo_db_bind_ip}}"
  notify: restart mongodb
