---
- name: Creating pnews group
  group: name={{pnews_group}} state=present

- name: Creating pnews user
  user: name={{pnews_user}} group={{pnews_group}} state=present

- name: "Installing some convencience utilities (system)"
  apt: name={{item}} state=present
  with_items:
    - vim
    - silversearcher-ag

- name: "Installing pip"
  easy_install: name=pip

- name: "Installing more utilities (python)"
  pip: name={{item}} state=present
  with_items:
    - httpie

- name: Installing nodeJS
  apt: name={{item}} state=present
  with_items:
    - nodejs
    - npm

- name: Creating symlink node pointing to nodeJS
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link

- name: "Cloning pnews from git"
  git: repo={{git_repo}} dest={{pnews_dir}} version={{git_version}}
  notify: restart pnews-web

- name: "Installing pnews dependencies using npm"
  npm: path={{pnews_web_dir}}
  notify: restart pnews-web

- name: "Installing pnews-web service"
  template: src="pnews-web-systemd" dest="{{pnews_web_systemd_config}}"
  notify: restart pnews-web

- name: "Enabling pnews-web at boot time"
  service: name=pnews-web enabled=yes