---
- name: Creating pnews group
  group: name={{pnews_group}} state=present

- name: Creating pnews user
  user: name={{pnews_user}} group={{pnews_group}} state=present

- name: "Installing some convenience utilities (system)"
  apt: name={{item}} state=present
  with_items:
    - git
    - python-setuptools # Installs easy_install
    - vim
    - silversearcher-ag
    - logrotate

- name: "Installing pip"
  easy_install: name=pip

- name: "Installing more utilities (python)"
  pip: name={{item}} state=present
  with_items:
    - httpie

- name: Installing nodeJS
  apt: name={{item}} state=present
  with_items:
    - nodejs
    - npm

- name: Creating symlink node pointing to nodeJS
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
